export const FETCH_DEVICES = 'FETCH_DEVICES';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const FETCH_DEVICE = 'FETCH_DEVICE';
export const TOGGLE_DEVICE = 'TOGGLE_DEVICE';
export const UPDATE_DEVICE_STATE = 'UPDATE_DEVICE_STATE';
export const CREATE_DEVICE = 'CREATE_DEVICE';
export const SET_HOST = 'SET_HOST';
